/*

   BLIS
   An object-based framework for developing high-performance BLAS-like
   libraries.

   Copyright (C) 2014, The University of Texas at Austin
   Copyright (C) 2020 - 2026, Advanced Micro Devices, Inc. All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are
   met:
    - Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    - Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    - Neither the name(s) of the copyright holder(s) nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "blis.h"

#if defined(BLIS_KERNELS_ZEN4)

// -----------------------------------------------------------------------------
// Per (arch, datatype) dispatch macros.
//
// AVX512 and AVX2 paths call the n-kernel directly and return -- the
// kernel handles its own ST/MT dispatch and non-unit incy internally, so the
// post-switch wrapper (packing + OpenMP) is bypassed.
// -----------------------------------------------------------------------------
#define ZEN4_s \
    bli_sgemv_n_zen4_int \
    ( \
      transa, \
      conjx, \
      m, \
      n, \
      alpha, \
      a, rs_a, cs_a, \
      x, incx, \
      beta, \
      y, incy, \
      cntx \
    ); \
    AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
    return;

#define ZEN4_d \
    bli_dgemv_n_zen4_int \
    ( \
      transa, \
      conjx, \
      m, \
      n, \
      alpha, \
      a, rs_a, cs_a, \
      x, incx, \
      beta, \
      y, incy, \
      cntx \
    ); \
    AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
    return;

/* Complex N-kernels (generated by GENERATE_ROOT_KERNEL) do not have a
   trans→M-FNAME fallback like s/d (there is no bli_cgemv_m_zen*_int).
   So only dispatch here when transa is no-transpose; otherwise let
   control fall through to the default axpyf path which handles trans
   via bli_set_dims_incs_with_trans. */
#define ZEN4_c \
    if (transa == BLIS_NO_TRANSPOSE) { \
      bli_cgemv_n_zen4_int \
      ( \
        transa, \
        conjx, \
        m, \
        n, \
        alpha, \
        a, rs_a, cs_a, \
        x, incx, \
        beta, \
        y, incy, \
        cntx \
      ); \
      AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
      return; \
    }

#define ZEN4_z \
    if (transa == BLIS_NO_TRANSPOSE) { \
      bli_zgemv_n_zen4_int \
      ( \
        transa, \
        conjx, \
        m, \
        n, \
        alpha, \
        a, rs_a, cs_a, \
        x, incx, \
        beta, \
        y, incy, \
        cntx \
      ); \
      AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
      return; \
    }

#else
    #define ZEN4_s
    #define ZEN4_d
    #define ZEN4_c
    #define ZEN4_z
    
#endif

#define ZEN_s \
    bli_sgemv_n_zen_int \
    ( \
      transa, \
      conjx, \
      m, \
      n, \
      alpha, \
      a, rs_a, cs_a, \
      x, incx, \
      beta, \
      y, incy, \
      cntx \
    ); \
    AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
    return;

#define ZEN_d \
    bli_dgemv_n_zen_int \
    ( \
        transa, \
        conjx, \
        m, \
        n, \
        alpha, \
        a, rs_a, cs_a, \
        x, incx, \
        beta, \
        y, incy, \
        cntx \
    ); \
    AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
    return;

#define ZEN_c \
    if (transa == BLIS_NO_TRANSPOSE) { \
      bli_cgemv_n_zen_int \
      ( \
          transa, \
          conjx, \
          m, \
          n, \
          alpha, \
          a, rs_a, cs_a, \
          x, incx, \
          beta, \
          y, incy, \
          cntx \
      ); \
      AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
      return; \
    }

#define ZEN_z \
    if (transa == BLIS_NO_TRANSPOSE) { \
      bli_zgemv_n_zen_int \
      ( \
          transa, \
          conjx, \
          m, \
          n, \
          alpha, \
          a, rs_a, cs_a, \
          x, incx, \
          beta, \
          y, incy, \
          cntx \
      ); \
      AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3) \
      return; \
    }

// ZEN6/ZEN5/ZEN4 map to the AVX-512 (ZEN4) kernels and ZEN3/ZEN2/ZEN map to
// the AVX2 (ZEN) kernels; this grouping is now expressed via
// bli_arch_isa_tier() and the two tier cases in the switch below, so the
// per-arch alias macros (ZEN6_*, ZEN5_*, ZEN3_*, ZEN2_*) are no longer needed.

#undef  GENTFUNC
#define GENTFUNC( ctype, ch, varname ) \
\
void PASTEMAC(ch,varname) \
     ( \
       trans_t transa, \
       conj_t  conjx, \
       dim_t   m, \
       dim_t   n, \
       ctype*  alpha, \
       ctype*  a, inc_t rs_a, inc_t cs_a, \
       ctype*  x, inc_t incx, \
       ctype*  beta, \
       ctype*  y, inc_t incy, \
       cntx_t* cntx  \
     ) \
{ \
\
    AOCL_DTL_TRACE_ENTRY(AOCL_DTL_LEVEL_TRACE_3); \
\
    bli_init_once(); \
\
    if(cntx == NULL) cntx = bli_gks_query_cntx(); \
\
    const num_t dt = PASTEMAC(ch,type); \
\
    arch_t arch_id = bli_arch_query_id_internal(); \
\
    dim_t b_fuse; \
\
    PASTECH(ch, axpyf_ker_ft)   axpyf_kr_ptr = NULL; \
    PASTECH(ch, scal2v_ker_ft)  scal2v_kr_ptr = NULL; \
    PASTECH(ch, scalv_ker_ft)   scalv_kr_ptr = NULL; \
    PASTECH(ch, copyv_ker_ft)   copyv_kr_ptr = NULL; \
\
    ctype*  A1; \
    ctype*  x1; \
    ctype*  y1; \
    dim_t   i; \
    dim_t   f; \
    dim_t   n_elem, n_iter; \
    inc_t   rs_at, cs_at; \
    conj_t  conja; \
\
    bli_set_dims_incs_with_trans( transa, \
                                  m, n, rs_a, cs_a, \
                                  &n_elem, &n_iter, &rs_at, &cs_at ); \
\
    conja = bli_extract_conj( transa ); \
\
    /* Dispatch on ISA capability tier rather than on individual arch_id \
       values. bli_arch_isa_tier() is the single place that maps a Zen \
       arch to its tier, so new Zen parts only need to be added there. */ \
    switch ( bli_arch_isa_tier( arch_id ) ) \
    { \
    case BLIS_ISA_TIER_AVX512: \
        PASTECH(ZEN4_, ch)     \
        /* s/d call-and-return above. For complex-transpose ZEN4_{c,z} \
           does nothing, so control fall through to the AVX2 case (whose \
           guard is also false) and on to default (the axpyf path). */ /* fall through */ \
    case BLIS_ISA_TIER_AVX2:                 \
        PASTECH(ZEN_, ch) /* fall through */ \
    case BLIS_ISA_TIER_GENERIC:              \
    default:                                 \
        /* For non-Zen architectures, query the context if it is NULL */ \
        if (cntx == NULL) cntx = bli_gks_query_cntx(); \
\
       /* Query the context for the kernel function pointers for */ \
       /* AXPYF, SCALV, COPYV and corresponding fusing */           \
       /* factor of AXPYF kernel */                                 \
     \
        axpyf_kr_ptr = bli_cntx_get_l1f_ker_dt(dt, BLIS_AXPYF_KER, cntx); \
        b_fuse       = bli_cntx_get_blksz_def_dt(dt, BLIS_AF, cntx);      \
        scalv_kr_ptr = bli_cntx_get_l1v_ker_dt(dt, BLIS_SCALV_KER, cntx); \
        copyv_kr_ptr = bli_cntx_get_l1v_ker_dt(dt, BLIS_COPYV_KER, cntx); \
    } \
\
    /*
        Memory pool declarations for packing vector Y.
    */\
    mem_t mem_bufY;\
    rntm_t rntm;\
    ctype* y_buf = y;\
    inc_t buf_incy = incy;\
\
    /*
        Boolean to check if the y has been packed
        and memory needs to be freed in the end
    */\
    bool is_y_temp_buf_created = FALSE;\
\
    /*
      If alpha is equal to zero, y is only scaled by beta and returned.
      In this case, packing and unpacking y will be costly and it is
      avoided.
    */\
    if (incy > 1 && (!PASTEMAC(ch,eq0)( *alpha )))\
    {\
        /*
            Initialize mem pool buffer to NULL and size to 0
            "buf" and "size" fields are assigned once memory
            is allocated from the pool in bli_pba_acquire_m().
            This will ensure bli_mem_is_alloc() will be passed on
            an allocated memory if created or a NULL .
        */\
        mem_bufY.pblk.buf = NULL;\
        mem_bufY.pblk.block_size = 0;\
        mem_bufY.buf_type = 0;\
        mem_bufY.size = 0;\
        mem_bufY.pool = NULL;\
\
        /*
        In order to get the buffer from pool via rntm access to memory broker
        is needed.Following are initializations for rntm
        */\
\
        bli_rntm_init_from_global(&rntm);\
        bli_rntm_set_num_threads_only(1, &rntm);\
        bli_pba_rntm_set_pba(&rntm);\
\
        /*
            Calculate the size required for n_elem double elements in vector Y.
        */\
        size_t buffer_size = n_elem * sizeof(ctype);\
\
        /*
            Acquire a Buffer(n_elem*size(double)) from the memory broker
            and save the associated mem_t entry to mem_bufY.
        */\
        bli_pba_acquire_m(&rntm,\
                            buffer_size,\
                            BLIS_BUFFER_FOR_B_PANEL,\
                            &mem_bufY);\
\
        /*
            Continue packing Y if buffer memory is allocated
        */\
        if ((bli_mem_is_alloc(&mem_bufY)))\
        {\
            y_buf = bli_mem_buffer(&mem_bufY);\
            buf_incy = 1;\
            scal2v_kr_ptr = bli_cntx_get_l1v_ker_dt( dt, BLIS_SCAL2V_KER, cntx );\
\
            /*
                Invoke the SCAL2V function using the function pointer
            */\
            scal2v_kr_ptr\
            (\
                BLIS_NO_CONJUGATE,\
                n_elem,\
                beta,\
                y, incy,\
                y_buf, buf_incy,\
                cntx\
            );\
\
            /*
                Set y is packed as the memory allocation was
                successful and contents have been copied
            */\
            is_y_temp_buf_created = TRUE;\
        }\
    }\
    else\
    {\
        /*
            Invoke the SCALV function using the function pointer
        */\
\
        scalv_kr_ptr\
        (\
            BLIS_NO_CONJUGATE,\
            n_elem,\
            beta,\
            y_buf, buf_incy,\
            cntx\
        );\
    }\
\
    /*
        If alpha is zero(0), we only need to scalv y and return
    */\
    if (PASTEMAC(ch,eq0)( *alpha ))\
    {\
        /*
            Return early for alpha is zero(0)
        */\
        return;\
    }\
\
    for ( i = 0; i < n_iter; i += f ) \
    { \
        f  = bli_determine_blocksize_dim_f( i, n_iter, b_fuse ); \
\
        A1 = a + (0  )*rs_at + (i  )*cs_at; \
        x1 = x + (i  )*incx; \
        y1 = y_buf + (0  )* buf_incy; \
\
        /* y = y + alpha * A1 * x1; */ \
        axpyf_kr_ptr \
        ( \
          conja, \
          conjx, \
          n_elem, \
          f, \
          alpha, \
          A1, rs_at, cs_at, \
          x1, incx, \
          y1, buf_incy, \
          cntx  \
        ); \
    } \
\
    /*
        Check if temp y buffer was used for compute
    */\
    if (is_y_temp_buf_created)\
    {\
        /*
            Store the result from unit strided y_buf to non-unit strided Y
            Invoke the COPYV function using the function pointer
        */\
\
        copyv_kr_ptr\
        (\
            BLIS_NO_CONJUGATE,\
            n_elem,\
            y_buf, buf_incy,\
            y, incy,\
            cntx\
        );\
\
        /* Return the buffer to pool */\
        bli_pba_release(&rntm, &mem_bufY);\
  }\
\
    AOCL_DTL_TRACE_EXIT(AOCL_DTL_LEVEL_TRACE_3); \
}

INSERT_GENTFUNC_BASIC0( gemv_unf_var2 )
