void f2c_cladiv_( bla_scomplex * ret_val, bla_scomplex *x, bla_scomplex *y );
void f2c_zladiv_( bla_dcomplex * ret_val, bla_dcomplex *x, bla_dcomplex *y );
bla_logical f2c_disnan_( bla_double *din );
bla_logical f2c_dlaisnan_( bla_double *din1, bla_double *din2 );
bla_logical f2c_sisnan_( bla_real *sin__ );
bla_logical f2c_slaisnan_( bla_real *sin1, bla_real *sin2 );
bla_integer f2c_ieeeck_( bla_integer *ispec, bla_real *zero, bla_real *one );
bla_integer f2c_ilaclc_( bla_integer *m, bla_integer *n, bla_scomplex *a, bla_integer *lda );
bla_integer f2c_ilaclr_( bla_integer *m, bla_integer *n, bla_scomplex *a, bla_integer *lda );
bla_integer f2c_iladlc_( bla_integer *m, bla_integer *n, bla_double *a, bla_integer *lda );
bla_integer f2c_iladlr_( bla_integer *m, bla_integer *n, bla_double *a, bla_integer *lda );
bla_integer f2c_ilaenv_( bla_integer *ispec, char *name__, char *opts, bla_integer *n1, bla_integer *n2, bla_integer *n3, bla_integer *n4, ftnlen name_len, ftnlen opts_len );
bla_integer f2c_ilaslc_( bla_integer *m, bla_integer *n, bla_real *a, bla_integer *lda );
bla_integer f2c_ilaslr_( bla_integer *m, bla_integer *n, bla_real *a, bla_integer *lda );
bla_integer f2c_ilazlc_( bla_integer *m, bla_integer *n, bla_dcomplex *a, bla_integer *lda );
bla_integer f2c_ilazlr_( bla_integer *m, bla_integer *n, bla_dcomplex *a, bla_integer *lda );
bla_integer f2c_iparmq_( bla_integer *ispec, char *name__, char *opts, bla_integer *n, bla_integer *ilo, bla_integer *ihi, bla_integer *lwork, ftnlen name_len, ftnlen opts_len );
bla_real f2c_clanhe_( char *norm, char *uplo, bla_integer *n, bla_scomplex *a, bla_integer *lda, bla_real *work, ftnlen norm_len, ftnlen uplo_len );
bla_real f2c_sladiv2_( bla_real *a, bla_real *b, bla_real *c__, bla_real *d__, bla_real *r__, bla_real *t );
bla_real f2c_slanst_( char *norm, bla_integer *n, bla_real *d__, bla_real *e, ftnlen norm_len );
bla_real f2c_slansy_( char *norm, char *uplo, bla_integer *n, bla_real *a, bla_integer *lda, bla_real * work, ftnlen norm_len, ftnlen uplo_len );
bla_real f2c_slapy2_( bla_real *x, bla_real *y );
bla_real f2c_slapy3_( bla_real *x, bla_real *y, bla_real *z__ );
bla_double f2c_dladiv2_( bla_double *a, bla_double *b, bla_double *c__, bla_double *d__, bla_double *r__, bla_double *t );
bla_double f2c_dlanst_( char *norm, bla_integer *n, bla_double *d__, bla_double *e, ftnlen norm_len );
bla_double f2c_dlansy_( char *norm, char *uplo, bla_integer *n, bla_double *a, bla_integer *lda, bla_double *work, ftnlen norm_len, ftnlen uplo_len );
bla_double f2c_dlapy2_( bla_double *x, bla_double *y );
bla_double f2c_dlapy3_( bla_double *x, bla_double *y, bla_double *z__ );
bla_double f2c_zlanhe_( char *norm, char *uplo, bla_integer *n, bla_dcomplex *a, bla_integer *lda, bla_double *work, ftnlen norm_len, ftnlen uplo_len );
int f2c_cheev_( char *jobz, char *uplo, bla_integer *n, bla_scomplex *a, bla_integer *lda, bla_real *w, bla_scomplex *work, bla_integer *lwork, bla_real *rwork, bla_integer *info, ftnlen jobz_len, ftnlen uplo_len );
int f2c_chetd2_( char *uplo, bla_integer *n, bla_scomplex *a, bla_integer *lda, bla_real *d__, bla_real *e, bla_scomplex *tau, bla_integer *info, ftnlen uplo_len );
int f2c_chetrd_( char *uplo, bla_integer *n, bla_scomplex *a, bla_integer *lda, bla_real *d__, bla_real *e, bla_scomplex *tau, bla_scomplex *work, bla_integer *lwork, bla_integer *info, ftnlen uplo_len );
int f2c_clacgv_( bla_integer *n, bla_scomplex *x, bla_integer *incx );
int f2c_clarf_( char *side, bla_integer *m, bla_integer *n, bla_scomplex *v, bla_integer *incv, bla_scomplex *tau, bla_scomplex *c__, bla_integer *ldc, bla_scomplex * work, ftnlen side_len );
int f2c_clarfb_( char *side, char *trans, char *direct, char * storev, bla_integer *m, bla_integer *n, bla_integer *k, bla_scomplex *v, bla_integer *ldv, bla_scomplex *t, bla_integer *ldt, bla_scomplex *c__, bla_integer *ldc, bla_scomplex *work, bla_integer *ldwork, ftnlen side_len, ftnlen trans_len, ftnlen direct_len, ftnlen storev_len );
int f2c_clarfg_( bla_integer *n, bla_scomplex *alpha, bla_scomplex *x, bla_integer * incx, bla_scomplex *tau );
int f2c_clarft_( char *direct, char *storev, bla_integer *n, bla_integer * k, bla_scomplex *v, bla_integer *ldv, bla_scomplex *tau, bla_scomplex *t, bla_integer *ldt, ftnlen direct_len, ftnlen storev_len );
int f2c_clascl_( char *type__, bla_integer *kl, bla_integer *ku, bla_real * cfrom, bla_real *cto, bla_integer *m, bla_integer *n, bla_scomplex *a, bla_integer *lda, bla_integer *info, ftnlen type_len );
int f2c_claset_( char *uplo, bla_integer *m, bla_integer *n, bla_scomplex * alpha, bla_scomplex *beta, bla_scomplex *a, bla_integer *lda, ftnlen uplo_len );
int f2c_clasr_( char *side, char *pivot, char *direct, bla_integer *m, bla_integer *n, bla_real *c__, bla_real *s, bla_scomplex *a, bla_integer *lda, ftnlen side_len, ftnlen pivot_len, ftnlen direct_len );
int f2c_classq_( bla_integer *n, bla_scomplex *x, bla_integer *incx, bla_real * scale, bla_real *sumsq );
int f2c_clatrd_( char *uplo, bla_integer *n, bla_integer *nb, bla_scomplex *a, bla_integer *lda, bla_real *e, bla_scomplex *tau, bla_scomplex *w, bla_integer *ldw, ftnlen uplo_len );
int f2c_csteqr_( char *compz, bla_integer *n, bla_real *d__, bla_real *e, bla_scomplex *z__, bla_integer *ldz, bla_real *work, bla_integer *info, ftnlen compz_len );
int f2c_cung2l_( bla_integer *m, bla_integer *n, bla_integer *k, bla_scomplex *a, bla_integer *lda, bla_scomplex *tau, bla_scomplex *work, bla_integer *info );
int f2c_cung2r_( bla_integer *m, bla_integer *n, bla_integer *k, bla_scomplex *a, bla_integer *lda, bla_scomplex *tau, bla_scomplex *work, bla_integer *info );
int f2c_cungql_( bla_integer *m, bla_integer *n, bla_integer *k, bla_scomplex *a, bla_integer *lda, bla_scomplex *tau, bla_scomplex *work, bla_integer *lwork, bla_integer * info );
int f2c_cungqr_( bla_integer *m, bla_integer *n, bla_integer *k, bla_scomplex *a, bla_integer *lda, bla_scomplex *tau, bla_scomplex *work, bla_integer *lwork, bla_integer * info );
int f2c_cungtr_( char *uplo, bla_integer *n, bla_scomplex *a, bla_integer *lda, bla_scomplex *tau, bla_scomplex *work, bla_integer *lwork, bla_integer *info, ftnlen uplo_len );
int f2c_dcombssq_( bla_double *v1, bla_double *v2 );
int f2c_dladiv_( bla_double *a, bla_double *b, bla_double *c__, bla_double *d__, bla_double *p, bla_double *q );
int f2c_dladiv1_( bla_double *a, bla_double *b, bla_double *c__, bla_double *d__, bla_double *p, bla_double *q );
int f2c_dlae2_( bla_double *a, bla_double *b, bla_double *c__, bla_double *rt1, bla_double *rt2 );
int f2c_dlaev2_( bla_double *a, bla_double *b, bla_double *c__, bla_double *rt1, bla_double *rt2, bla_double *cs1, bla_double *sn1 );
int f2c_dlarf_( char *side, bla_integer *m, bla_integer *n, bla_double *v, bla_integer *incv, bla_double *tau, bla_double *c__, bla_integer *ldc, bla_double *work, ftnlen side_len );
int f2c_dlarfb_( char *side, char *trans, char *direct, char * storev, bla_integer *m, bla_integer *n, bla_integer *k, bla_double *v, bla_integer * ldv, bla_double *t, bla_integer *ldt, bla_double *c__, bla_integer *ldc, bla_double *work, bla_integer *ldwork, ftnlen side_len, ftnlen trans_len, ftnlen direct_len, ftnlen storev_len );
int f2c_dlarfg_( bla_integer *n, bla_double *alpha, bla_double *x, bla_integer *incx, bla_double *tau );
int f2c_dlarft_( char *direct, char *storev, bla_integer *n, bla_integer * k, bla_double *v, bla_integer *ldv, bla_double *tau, bla_double *t, bla_integer *ldt, ftnlen direct_len, ftnlen storev_len );
int f2c_dlartg_( bla_double *f, bla_double *g, bla_double *cs, bla_double *sn, bla_double *r__ );
int f2c_dlascl_( char *type__, bla_integer *kl, bla_integer *ku, bla_double *cfrom, bla_double *cto, bla_integer *m, bla_integer *n, bla_double *a, bla_integer *lda, bla_integer *info, ftnlen type_len );
int f2c_dlaset_( char *uplo, bla_integer *m, bla_integer *n, bla_double * alpha, bla_double *beta, bla_double *a, bla_integer *lda, ftnlen uplo_len );
int f2c_dlasr_( char *side, char *pivot, char *direct, bla_integer *m, bla_integer *n, bla_double *c__, bla_double *s, bla_double *a, bla_integer * lda, ftnlen side_len, ftnlen pivot_len, ftnlen direct_len );
int f2c_dlasrt_( char *id, bla_integer *n, bla_double *d__, bla_integer * info, ftnlen id_len );
int f2c_dlassq_( bla_integer *n, bla_double *x, bla_integer *incx, bla_double *scale, bla_double *sumsq );
int f2c_dlatrd_( char *uplo, bla_integer *n, bla_integer *nb, bla_double * a, bla_integer *lda, bla_double *e, bla_double *tau, bla_double *w, bla_integer *ldw, ftnlen uplo_len );
int f2c_dorg2l_( bla_integer *m, bla_integer *n, bla_integer *k, bla_double * a, bla_integer *lda, bla_double *tau, bla_double *work, bla_integer *info );
int f2c_dorg2r_( bla_integer *m, bla_integer *n, bla_integer *k, bla_double * a, bla_integer *lda, bla_double *tau, bla_double *work, bla_integer *info );
int f2c_dorgql_( bla_integer *m, bla_integer *n, bla_integer *k, bla_double * a, bla_integer *lda, bla_double *tau, bla_double *work, bla_integer *lwork, bla_integer *info );
int f2c_dorgqr_( bla_integer *m, bla_integer *n, bla_integer *k, bla_double * a, bla_integer *lda, bla_double *tau, bla_double *work, bla_integer *lwork, bla_integer *info );
int f2c_dorgtr_( char *uplo, bla_integer *n, bla_double *a, bla_integer * lda, bla_double *tau, bla_double *work, bla_integer *lwork, bla_integer *info, ftnlen uplo_len );
int f2c_dsteqr_( char *compz, bla_integer *n, bla_double *d__, bla_double *e, bla_double *z__, bla_integer *ldz, bla_double *work, bla_integer *info, ftnlen compz_len );
int f2c_dsterf_( bla_integer *n, bla_double *d__, bla_double *e, bla_integer *info );
int f2c_dsyev_( char *jobz, char *uplo, bla_integer *n, bla_double *a, bla_integer *lda, bla_double *w, bla_double *work, bla_integer *lwork, bla_double *rwork, bla_integer *info, ftnlen jobz_len, ftnlen uplo_len );
int f2c_dsytd2_( char *uplo, bla_integer *n, bla_double *a, bla_integer * lda, bla_double *d__, bla_double *e, bla_double *tau, bla_integer *info, ftnlen uplo_len );
int f2c_dsytrd_( char *uplo, bla_integer *n, bla_double *a, bla_integer * lda, bla_double *d__, bla_double *e, bla_double *tau, bla_double * work, bla_integer *lwork, bla_integer *info, ftnlen uplo_len );
int f2c_scombssq_( bla_real *v1, bla_real *v2 );
int f2c_sladiv_( bla_real *a, bla_real *b, bla_real *c__, bla_real *d__, bla_real *p, bla_real *q );
int f2c_sladiv1_( bla_real *a, bla_real *b, bla_real *c__, bla_real *d__, bla_real *p, bla_real *q );
int f2c_slae2_( bla_real *a, bla_real *b, bla_real *c__, bla_real *rt1, bla_real *rt2 );
int f2c_slaev2_( bla_real *a, bla_real *b, bla_real *c__, bla_real *rt1, bla_real * rt2, bla_real *cs1, bla_real *sn1 );
int f2c_slarf_( char *side, bla_integer *m, bla_integer *n, bla_real *v, bla_integer *incv, bla_real *tau, bla_real *c__, bla_integer *ldc, bla_real *work, ftnlen side_len );
int f2c_slarfb_( char *side, char *trans, char *direct, char * storev, bla_integer *m, bla_integer *n, bla_integer *k, bla_real *v, bla_integer *ldv, bla_real *t, bla_integer *ldt, bla_real *c__, bla_integer *ldc, bla_real *work, bla_integer * ldwork, ftnlen side_len, ftnlen trans_len, ftnlen direct_len, ftnlen storev_len );
int f2c_slarfg_( bla_integer *n, bla_real *alpha, bla_real *x, bla_integer *incx, bla_real *tau );
int f2c_slarft_( char *direct, char *storev, bla_integer *n, bla_integer * k, bla_real *v, bla_integer *ldv, bla_real *tau, bla_real *t, bla_integer *ldt, ftnlen direct_len, ftnlen storev_len );
int f2c_slartg_( bla_real *f, bla_real *g, bla_real *cs, bla_real *sn, bla_real *r__ );
int f2c_slascl_( char *type__, bla_integer *kl, bla_integer *ku, bla_real * cfrom, bla_real *cto, bla_integer *m, bla_integer *n, bla_real *a, bla_integer *lda, bla_integer *info, ftnlen type_len );
int f2c_slaset_( char *uplo, bla_integer *m, bla_integer *n, bla_real *alpha, bla_real *beta, bla_real *a, bla_integer *lda, ftnlen uplo_len );
int f2c_slasr_( char *side, char *pivot, char *direct, bla_integer *m, bla_integer *n, bla_real *c__, bla_real *s, bla_real *a, bla_integer *lda, ftnlen side_len, ftnlen pivot_len, ftnlen direct_len );
int f2c_slasrt_( char *id, bla_integer *n, bla_real *d__, bla_integer *info, ftnlen id_len );
int f2c_slassq_( bla_integer *n, bla_real *x, bla_integer *incx, bla_real *scale, bla_real *sumsq );
int f2c_slatrd_( char *uplo, bla_integer *n, bla_integer *nb, bla_real *a, bla_integer *lda, bla_real *e, bla_real *tau, bla_real *w, bla_integer *ldw, ftnlen uplo_len );
int f2c_sorg2l_( bla_integer *m, bla_integer *n, bla_integer *k, bla_real *a, bla_integer *lda, bla_real *tau, bla_real *work, bla_integer *info );
int f2c_sorg2r_( bla_integer *m, bla_integer *n, bla_integer *k, bla_real *a, bla_integer *lda, bla_real *tau, bla_real *work, bla_integer *info );
int f2c_sorgql_( bla_integer *m, bla_integer *n, bla_integer *k, bla_real *a, bla_integer *lda, bla_real *tau, bla_real *work, bla_integer *lwork, bla_integer *info );
int f2c_sorgqr_( bla_integer *m, bla_integer *n, bla_integer *k, bla_real *a, bla_integer *lda, bla_real *tau, bla_real *work, bla_integer *lwork, bla_integer *info );
int f2c_sorgtr_( char *uplo, bla_integer *n, bla_real *a, bla_integer *lda, bla_real *tau, bla_real *work, bla_integer *lwork, bla_integer *info, ftnlen uplo_len );
int f2c_ssteqr_( char *compz, bla_integer *n, bla_real *d__, bla_real *e, bla_real *z__, bla_integer *ldz, bla_real *work, bla_integer *info, ftnlen compz_len );
int f2c_ssterf_( bla_integer *n, bla_real *d__, bla_real *e, bla_integer *info );
int f2c_ssyev_( char *jobz, char *uplo, bla_integer *n, bla_real *a, bla_integer *lda, bla_real *w, bla_real *work, bla_integer *lwork, bla_real *rwork, bla_integer *info, ftnlen jobz_len, ftnlen uplo_len );
int f2c_ssytd2_( char *uplo, bla_integer *n, bla_real *a, bla_integer *lda, bla_real *d__, bla_real *e, bla_real *tau, bla_integer *info, ftnlen uplo_len );
int f2c_ssytrd_( char *uplo, bla_integer *n, bla_real *a, bla_integer *lda, bla_real *d__, bla_real *e, bla_real *tau, bla_real *work, bla_integer *lwork, bla_integer * info, ftnlen uplo_len );
int f2c_zheev_( char *jobz, char *uplo, bla_integer *n, bla_dcomplex *a, bla_integer *lda, bla_double *w, bla_dcomplex *work, bla_integer *lwork, bla_double *rwork, bla_integer *info, ftnlen jobz_len, ftnlen uplo_len );
int f2c_zhetd2_( char *uplo, bla_integer *n, bla_dcomplex *a, bla_integer *lda, bla_double *d__, bla_double *e, bla_dcomplex *tau, bla_integer *info, ftnlen uplo_len );
int f2c_zhetrd_( char *uplo, bla_integer *n, bla_dcomplex *a, bla_integer *lda, bla_double *d__, bla_double *e, bla_dcomplex *tau, bla_dcomplex *work, bla_integer *lwork, bla_integer *info, ftnlen uplo_len );
int f2c_zlacgv_( bla_integer *n, bla_dcomplex *x, bla_integer *incx );
int f2c_zlarf_( char *side, bla_integer *m, bla_integer *n, bla_dcomplex *v, bla_integer *incv, bla_dcomplex *tau, bla_dcomplex *c__, bla_integer * ldc, bla_dcomplex *work, ftnlen side_len );
int f2c_zlarfb_( char *side, char *trans, char *direct, char * storev, bla_integer *m, bla_integer *n, bla_integer *k, bla_dcomplex *v, bla_integer *ldv, bla_dcomplex *t, bla_integer *ldt, bla_dcomplex *c__, bla_integer * ldc, bla_dcomplex *work, bla_integer *ldwork, ftnlen side_len, ftnlen trans_len, ftnlen direct_len, ftnlen storev_len );
int f2c_zlarfg_( bla_integer *n, bla_dcomplex *alpha, bla_dcomplex * x, bla_integer *incx, bla_dcomplex *tau );
int f2c_zlarft_( char *direct, char *storev, bla_integer *n, bla_integer * k, bla_dcomplex *v, bla_integer *ldv, bla_dcomplex *tau, bla_dcomplex * t, bla_integer *ldt, ftnlen direct_len, ftnlen storev_len );
int f2c_zlascl_( char *type__, bla_integer *kl, bla_integer *ku, bla_double *cfrom, bla_double *cto, bla_integer *m, bla_integer *n, bla_dcomplex *a, bla_integer *lda, bla_integer *info, ftnlen type_len );
int f2c_zlaset_( char *uplo, bla_integer *m, bla_integer *n, bla_dcomplex *alpha, bla_dcomplex *beta, bla_dcomplex *a, bla_integer * lda, ftnlen uplo_len );
int f2c_zlasr_( char *side, char *pivot, char *direct, bla_integer *m, bla_integer *n, bla_double *c__, bla_double *s, bla_dcomplex *a, bla_integer *lda, ftnlen side_len, ftnlen pivot_len, ftnlen direct_len );
int f2c_zlassq_( bla_integer *n, bla_dcomplex *x, bla_integer *incx, bla_double *scale, bla_double *sumsq );
int f2c_zlatrd_( char *uplo, bla_integer *n, bla_integer *nb, bla_dcomplex *a, bla_integer *lda, bla_double *e, bla_dcomplex *tau, bla_dcomplex *w, bla_integer *ldw, ftnlen uplo_len );
int f2c_zsteqr_( char *compz, bla_integer *n, bla_double *d__, bla_double *e, bla_dcomplex *z__, bla_integer *ldz, bla_double *work, bla_integer *info, ftnlen compz_len );
int f2c_zung2l_( bla_integer *m, bla_integer *n, bla_integer *k, bla_dcomplex *a, bla_integer *lda, bla_dcomplex *tau, bla_dcomplex * work, bla_integer *info );
int f2c_zung2r_( bla_integer *m, bla_integer *n, bla_integer *k, bla_dcomplex *a, bla_integer *lda, bla_dcomplex *tau, bla_dcomplex * work, bla_integer *info );
int f2c_zungql_( bla_integer *m, bla_integer *n, bla_integer *k, bla_dcomplex *a, bla_integer *lda, bla_dcomplex *tau, bla_dcomplex * work, bla_integer *lwork, bla_integer *info );
int f2c_zungqr_( bla_integer *m, bla_integer *n, bla_integer *k, bla_dcomplex *a, bla_integer *lda, bla_dcomplex *tau, bla_dcomplex * work, bla_integer *lwork, bla_integer *info );
int f2c_zungtr_( char *uplo, bla_integer *n, bla_dcomplex *a, bla_integer *lda, bla_dcomplex *tau, bla_dcomplex *work, bla_integer *lwork, bla_integer *info, ftnlen uplo_len );
